name: ci_meson

on:
  # Allow manual workflow triggering
  workflow_dispatch:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.y"
      - "**.l"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.y"
      - "**.l"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson test -C builddir/ -v --wrap='valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1'
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: |
        brew install gcc clang-format
        brew install flex bison
        echo "/opt/homebrew/opt/bison/bin" >> $GITHUB_PATH
        echo "/opt/homebrew/opt/flex/bin" >> $GITHUB_PATH
    - run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson test -C builddir/ -v
    - run: ninja -C builddir clang-format-check
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
